review_task:
  description: >
    Anomaly detectors are provided the results of reconciliation performed between two sources. This contains two sets of data. One is historical & the other real time. They are also be given metadata to understand what’s in the data.
    Expounding on the fields in the metadata:
    Key Columns: These are the columns based on which LHS (Left hand Side) or Source 1 data is matched with RHS (Right Hand Side) or Source 2 data.
    Criteria Columns: These are the column which are matched between LHS and RHS to mark the reconciliations as a Match or Break. These can be exact match or matching with some tolerance/buffer and is typically done by reconciliation rules engine.
    Derived Columns: New columns created during reconciliation process to facilitate break analysis.
    Historical Columns: Suggested column which can be used in conjunction with date columns to establish historical trends and patterns in the data.
    Date Columns: Date columns which can be used as a marker to study point in time data.
    Comment Columns: Documentation of corrective action taken or analysis. This could be empty in some cases.

    Verify the final report generated by the anomaly detection pipeline follows the following rules:
    RULE 1: Only breaks between data sources are to be classified as anomalies. Match situations in data sources are not anomalies.
    RULE 2: It is not necessary that a break is an anomaly. An anomaly occurs when there is a break in the data source which violates patterns observed in previous data such as non-uniform increase/decrease in values of criteria & derived columns. Any increase or decrease that occurs should be uniform across for it to not be an anomaly. 


    Rule 2 is extremely crucial & should be the primary point of focus for the reviewer. Some examples to guide the review process pertaining to this rule are as follows:

    -Data in source 1 is 10,000 & data in source 2 is 70,000 resulting in difference of 60,000. This is a break but not an anomaly if the break was of 40,000 & 20,000 in the two previous months as there is a uniform increase of 20,000 in break amount.
    -Data in source 1 is 20,000 & data in source 2 is 30,000 resulting in difference of 10,000. This is a break and an anomaly if the break was of 20,000 consistently in the past three months.
    -An all time low or an all time high in the balance difference does not necessarily mean an anomaly. If balance difference is at peak of 90,000 but  was 70,000 and 50,000 in previous months. This is not an anomaly as historical data shows trend of uniform increase of 20,000.
    
    Make your final conclusions only on basis of these rules & do not assume things on your own.

    Your final response must include:
    - Valid: True/False
    - Feedback: Provide commentary if the report fails any of the criteria.

    Anomaly Report to verify:
    {report}
  expected_output: >
     Pass: True/False
     Feedback: one sentence summary for each data point reviewed
  agent: anomaly_reviewer
